all: 
	g++ -fopenmp openmpk.cpp -o openmpk -lcrypto -lssl

	g++ -fopenmp openmp2.cpp -o openmp2 -lcrypto -lssl

	g++ pthreadk.cpp -lcrypto -lssl -lpthread -o pthreadk

	g++ pthreadk.cpp -lcrypto -lssl -lpthread -o pthread2
